### GET ALL

GET http://localhost:9090/entities
Accept: application/json

### ADD

POST http://localhost:9090/entity
Content-Type: application/json

{
  "name": "asde"
}

### DELETE

DELETE http://localhost:9090/entity/642683442
Content-Type: application/json